# Generated by Django 2.2.24 on 2022-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='holder_id_check',
            field=models.IntegerField(default=-1),
        ),
    ]
