# Generated by Django 2.2.24 on 2022-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220112_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('desc', models.TextField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
