# Generated by Django 2.2.24 on 2022-01-18 09:25

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220117_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', creditcards.models.CardNumberField(max_length=25)),
                ('unq_id', models.IntegerField()),
                ('true', models.CharField(default='None', max_length=9)),
            ],
        ),
    ]
