# Generated by Django 2.2.24 on 2022-01-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payholder',
            name='card',
        ),
    ]
