# Generated by Django 2.2.24 on 2022-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220128_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default='nan', max_length=999),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
