# Generated by Django 2.2.24 on 2022-01-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220128_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holder',
        ),
    ]
