# Generated by Django 2.2.24 on 2022-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220130_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField()),
                ('situation', models.TextField()),
            ],
        ),
    ]
