# Generated by Django 2.2.4 on 2022-02-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='client',
            field=models.TextField(),
        ),
    ]
