# Generated by Django 2.2.4 on 2022-02-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220207_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.TextField()),
                ('confirmed', models.BooleanField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
            ],
        ),
    ]
