# Generated by Django 2.2.4 on 2022-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
