# Generated by Django 2.2.4 on 2022-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220226_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.TextField(unique=True),
        ),
    ]
